# Formulae (CLI tools)
brew "uv"
brew "ruff"
brew "gh"
brew "hf"
brew "container"
brew "chezmoi"
brew "colima"
brew "docker"
brew "docker-compose"
brew "fnm"
brew "direnv"
brew "tmux"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "mas"
brew "cocoapods"
brew "pi-coding-agent"

# Casks (GUI apps)
cask "iterm2"
cask "visual-studio-code"
cask "font-hack-nerd-font"
cask "android-studio"
